# 张量的特殊乘法

## 1. 一维张量乘以二维张量

- 一维张量的维度须与二维张量第一维的维度相等。
- 得到的结果是一维的。

In [1]:
import torch

a = torch.tensor([2, 3, 4])
b = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])
a @ b

tensor([31, 40])

## 2. 两个三维张量相乘

- 两者第一维的维度须相等。
- 在第一维上，1与1相乘，2与2相乘；第二维和第三维使用普通的matmul乘法相乘。

In [2]:
# 创建两个张量
a = torch.randint(1, 5, [2, 3, 6])
b = torch.randint(1, 5, [2, 6, 3])

# 进行矩阵乘法
result = torch.matmul(a, b)

print(a, "\n", b, "\n", result)

tensor([[[4, 1, 4, 1, 2, 3],
         [3, 1, 1, 3, 3, 4],
         [2, 1, 3, 2, 4, 1]],

        [[3, 2, 4, 1, 1, 2],
         [3, 4, 1, 1, 2, 3],
         [3, 3, 1, 4, 2, 2]]]) 
 tensor([[[1, 4, 1],
         [2, 4, 3],
         [3, 4, 1],
         [4, 3, 4],
         [4, 2, 2],
         [3, 3, 1]],

        [[2, 4, 3],
         [1, 2, 4],
         [4, 3, 2],
         [1, 1, 2],
         [2, 1, 1],
         [2, 3, 2]]]) 
 tensor([[[39, 52, 22],
         [44, 47, 29],
         [40, 41, 25]],

        [[31, 36, 32],
         [25, 35, 37],
         [25, 33, 37]]])
