以下内容是《龙良曲 PyTorch 入门到实战》的学习笔记。

PyTorch 张量的 API 和 Numpy 数组的 API 有很多相似的地方。

In [1]:
import torch

# 1. 创建张量 1

In [2]:
# 创建 0 维张量（标量）
a = torch.tensor(2)
a, a.shape, a.dim()

(tensor(2), torch.Size([]), 0)

In [3]:
# 创建 1 维张量
b = torch.tensor([1, 2])
b, b.shape, b.dim()

(tensor([1, 2]), torch.Size([2]), 1)

`torch.Size([2])`：`[2]` 表示张量只有一个维度，且该维度的大小为 2，意味着张量是一个长度为 2 的一维向量。

In [4]:
# 创建 2 维张量
c = torch.rand(2, 3)  # torch.rand 是从均匀分布 [0, 1) 中随机采样
c, c.shape, c.dim()

(tensor([[0.9686, 0.7946, 0.7449],
         [0.1201, 0.4476, 0.0770]]),
 torch.Size([2, 3]),
 2)

In [5]:
# 创建 3 维张量
d = torch.rand(2, 3, 4)
d, d.shape, d.dim()

(tensor([[[0.8538, 0.5267, 0.1124, 0.2672],
          [0.2907, 0.2545, 0.0343, 0.3990],
          [0.7130, 0.4403, 0.8850, 0.5279]],
 
         [[0.0545, 0.9124, 0.6255, 0.5443],
          [0.7342, 0.0985, 0.8456, 0.8161],
          [0.8040, 0.5386, 0.0100, 0.5233]]]),
 torch.Size([2, 3, 4]),
 3)

In [6]:
# 创建 4 维张量
e = torch.rand(2, 3, 4, 5)
e, e.shape, e.dim()

(tensor([[[[0.9297, 0.9197, 0.7691, 0.5129, 0.8893],
           [0.3486, 0.4386, 0.3001, 0.9997, 0.8681],
           [0.7796, 0.7566, 0.6094, 0.0308, 0.5724],
           [0.7797, 0.8262, 0.8077, 0.0019, 0.3176]],
 
          [[0.2055, 0.4491, 0.8261, 0.8498, 0.9019],
           [0.1624, 0.9341, 0.1536, 0.5654, 0.1507],
           [0.5357, 0.2965, 0.8886, 0.3911, 0.6500],
           [0.7012, 0.8582, 0.4083, 0.5539, 0.6178]],
 
          [[0.2372, 0.9600, 0.6302, 0.3125, 0.7110],
           [0.5503, 0.2442, 0.2083, 0.3097, 0.6085],
           [0.1198, 0.4057, 0.6642, 0.3791, 0.8297],
           [0.0814, 0.0544, 0.3282, 0.2089, 0.2893]]],
 
 
         [[[0.8736, 0.2800, 0.7400, 0.7517, 0.5123],
           [0.5182, 0.3899, 0.5260, 0.4197, 0.1784],
           [0.3615, 0.5219, 0.4403, 0.3220, 0.5847],
           [0.6244, 0.5133, 0.8042, 0.0471, 0.8485]],
 
          [[0.4582, 0.1989, 0.1641, 0.0227, 0.6702],
           [0.1181, 0.7702, 0.4306, 0.7295, 0.7457],
           [0.9274, 0.5206, 0.8

In [7]:
e.numel()  # number of element, 2*3*4*5=120

120

In [8]:
# 设置张量的默认数据类型
# torch.set_default_tensor_type(torch.DoubleTensor)

# 2. 创建张量 2

## 2.1 从分布中随机采样

In [9]:
# 从均匀分布 [0, 1) 中随机采样
a = torch.rand(2, 3)  
a

tensor([[0.4009, 0.3405, 0.9747],
        [0.3479, 0.6446, 0.9658]])

In [10]:
# 从 [1, 10) 中随机采样整数
torch.randint(1, 10, [3,4])  

tensor([[9, 9, 2, 3],
        [1, 7, 3, 9],
        [9, 5, 2, 8]])

In [11]:
# 从标准正态分布 N(0, 1) 中随机采样
torch.randn(3, 4)  # 3 行 4 列

tensor([[ 0.0087,  0.4315,  0.0839,  0.0460],
        [-0.7226,  1.0041,  1.0856, -2.4482],
        [-0.8696, -0.8343,  0.8393,  1.2507]])

In [12]:
# 从正态分布中随机采样
torch.normal(mean=0, std=4, size=(2, 3))

tensor([[ 3.0445,  6.6696,  7.9885],
        [ 6.7185, -0.5992, -1.3827]])

## 2.2 使用特定值填充张量

In [13]:
# 使用任意值填充张量
torch.full([2,3], 6)  # 2 行 3 列，填充值为 6

tensor([[6, 6, 6],
        [6, 6, 6]])

In [14]:
# 使用 1 填充张量
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# 使用 0 填充张量
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
# 使用 1 填充张量对角线
torch.eye(3, 4)  # 使用 1 填充 3 行 4 列张量对角线

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

## 2.3 生成序列张量

In [17]:
# 生成整数序列张量
torch.arange(0, 10, 2)  # 采样 [0,10) 之间的整数，步长为 2，默认为 1

tensor([0, 2, 4, 6, 8])

In [18]:
# 生成等间隔序列张量
torch.linspace(0, 10, steps=4)  # 起始值为 0, 结束值为 10, steps 指定生成的样本数量为 4

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [19]:
# 生成等间隔序列张量，并使用指定底数做指数运算
torch.logspace(0, 10, steps=11, base=2)  # 起始值为 0, 结束值为 10, base 指定底数为 2，默认为 10

tensor([1.0000e+00, 2.0000e+00, 4.0000e+00, 8.0000e+00, 1.6000e+01, 3.2000e+01,
        6.4000e+01, 1.2800e+02, 2.5600e+02, 5.1200e+02, 1.0240e+03])

## 2.4 生成随机索引种子张量

In [20]:
idx = torch.randperm(10)  # 范围为 [0, 10)
idx

tensor([9, 1, 5, 3, 8, 2, 6, 4, 7, 0])

# 3. 索引与切片

In [21]:
a = torch.rand(3, 4, 18, 5)
b = torch.randn(3, 4)

## 3.1 直接索引

In [22]:
a[0].shape

torch.Size([4, 18, 5])

In [23]:
a[0, 0].shape

torch.Size([18, 5])

In [24]:
a[0, 0, 2, 4].shape

torch.Size([])

## 3.2 切片

In [25]:
a.shape

torch.Size([3, 4, 18, 5])

In [26]:
a[:2].shape

torch.Size([2, 4, 18, 5])

In [27]:
a[:2, :1, :, :].shape

torch.Size([2, 1, 18, 5])

In [28]:
a[:2, 1:, :, :].shape

torch.Size([2, 3, 18, 5])

In [29]:
a[:2, -1:, :, :].shape

torch.Size([2, 1, 18, 5])

In [30]:
a[:, :-1, :, :].shape

torch.Size([3, 3, 18, 5])

## 3.3 间隔采样

In [31]:
a.shape

torch.Size([3, 4, 18, 5])

`[n : m : k]` 代表的是在 [n: m) 这一段采样，每 k 个采样一次。
k 代表的是间隔，间隔可正可负，正值代表正向挑取，负值代表反向挑取。
当k为正的时候起始索引应该小于结束索引；当k为负的时候起始索引应该大于结束索引，因为在倒序来看，首先是索引值大的被取到，然后才是索引值小的。

In [32]:
a[:, :, 0:18:2, :].shape

torch.Size([3, 4, 9, 5])

In [33]:
a[:, :, ::2, :].shape  # ::2 表示从全序列采样，每 2 个采样一次

torch.Size([3, 4, 9, 5])

## 3.4 根据特定索引采样

In [34]:
a.shape

torch.Size([3, 4, 18, 5])

**`a.index_select(2, torch.tensor([2,5,7,15])).shape`：**

对第 3 维的 `[2,5,7,15]` 进行采样，`[2,5,7,15]` 必须是一维 tensor，列表形式会报错。

In [35]:
a.index_select(2, torch.tensor([2,5,7,15])).shape

torch.Size([3, 4, 4, 5])

## 3.5 根据掩码采样

In [36]:
b

tensor([[-0.5964, -0.4281,  0.4886, -0.2092],
        [-0.7341, -2.2482, -0.2632, -1.3791],
        [-1.2898,  0.5030,  0.2307, -1.8632]])

In [37]:
mask = b.ge(0.5)  # great equal 为大于等于，取 b 中大于等于 0.5 的元素
mask

tensor([[False, False, False, False],
        [False, False, False, False],
        [False,  True, False, False]])

In [38]:
torch.masked_select(b, mask)

tensor([0.5030])

## 3.6 打平之后采样

In [39]:
b

tensor([[-0.5964, -0.4281,  0.4886, -0.2092],
        [-0.7341, -2.2482, -0.2632, -1.3791],
        [-1.2898,  0.5030,  0.2307, -1.8632]])

In [40]:
torch.take(b, torch.tensor([0, 3, 10, 11]))

tensor([-0.5964, -0.2092,  0.2307, -1.8632])

## 3.7 ... 全取

In [41]:
a.shape

torch.Size([3, 4, 18, 5])

... 取连续区间内的所有维度的所有内容

In [42]:
a[2, ...].shape  # 第 1 维取的是索引为 2 的内容，其余维度的内容全取

torch.Size([4, 18, 5])

In [43]:
a[:, 3, ...].shape

torch.Size([3, 18, 5])

In [44]:
a[..., :3].shape

torch.Size([3, 4, 18, 3])

In [45]:
a[2:, ..., :3].shape

torch.Size([1, 4, 18, 3])

# 4. 维度变换 

In [46]:
a = torch.rand(4, 1, 28, 28)

## 4.1 view() 和 reshape()：重塑数据 shape，两者完全等同

In [47]:
a.view(4, 1*28*28)  # 变换成 2 维

tensor([[0.0715, 0.3341, 0.9545,  ..., 0.7326, 0.9764, 0.2340],
        [0.3593, 0.5125, 0.3480,  ..., 0.3869, 0.4530, 0.9567],
        [0.2802, 0.2535, 0.4238,  ..., 0.2034, 0.6537, 0.8120],
        [0.8499, 0.3464, 0.5340,  ..., 0.3051, 0.6123, 0.7139]])

In [48]:
a.reshape(4, 1*28*28)

tensor([[0.0715, 0.3341, 0.9545,  ..., 0.7326, 0.9764, 0.2340],
        [0.3593, 0.5125, 0.3480,  ..., 0.3869, 0.4530, 0.9567],
        [0.2802, 0.2535, 0.4238,  ..., 0.2034, 0.6537, 0.8120],
        [0.8499, 0.3464, 0.5340,  ..., 0.3051, 0.6123, 0.7139]])

## 4.2 unsqueeze(): 增加维度

unsqueeze() 增加维度不会改变数据，只是增加一个维度，这个维度的具体含义由自己定义。

In [49]:
a.shape

torch.Size([4, 1, 28, 28])

In [50]:
a.unsqueeze(0).shape  # 在第一维之前增加一个维度

torch.Size([1, 4, 1, 28, 28])

In [51]:
a.unsqueeze(-1).shape  # 在最后一维之后增加一个维度

torch.Size([4, 1, 28, 28, 1])

In [52]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [53]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

## 4.3 squeeze(): 减少维度

只能去掉 size 为 1 的维度，对 size 不为 1 的维度执行此操作，原数据保持不变。

() 内无参数时，去掉所有 size 为 1 的维度。

In [54]:
a.shape

torch.Size([4, 1, 28, 28])

In [55]:
a.squeeze().shape

torch.Size([4, 28, 28])

In [56]:
a.squeeze(1).shape  

torch.Size([4, 28, 28])

In [57]:
a.squeeze(0).shape  

torch.Size([4, 1, 28, 28])

In [58]:
a.squeeze(-3).shape  

torch.Size([4, 28, 28])

## 4.4 expand(): 增加某一维度的 size

只能增加 size 为 1 的维度的 size，增加 size 不为 1 的维度的 size 会报错。

注意：增加某一维度的 size 是对既有数据的复制！

-1 表示此维度的 size 保持不变。

In [59]:
a.shape, a.numel()

(torch.Size([4, 1, 28, 28]), 3136)

In [60]:
a.expand(4, 2, 28, 28).shape, a.expand(4, 2, 28, 28).numel()

(torch.Size([4, 2, 28, 28]), 6272)

In [61]:
a.expand(-1, 2, -1, -1).shape

torch.Size([4, 2, 28, 28])

## 4.5 使用示例：不同维度数据相加

In [62]:
# 创建一个包含 32 个数据的一维张量
b = torch.rand(32)

# 创建一个四维张量，其中第二维的 size 为 32
c = torch.rand(4, 32, 15, 15)

# 使用 unsqueeze() 增加 b 的维度
b = b.unsqueeze(0).unsqueeze(2).unsqueeze(3)

# 使用 expand() 增加 b 的维度的 size
b = b.expand(4, 32, 15, 15)

# 将 b 和 c 相加
(b + c).shape

torch.Size([4, 32, 15, 15])

## 4.6 t(): 交换维度

.t() 只能用于二维张量交换维度，不能用于其他高维张量，返回输入张量的转置版本。

In [63]:
d = torch.rand(3, 4)

In [64]:
d.t().shape

torch.Size([4, 3])

## 4.7 transpose(): 交换维度

transpose() 可以用于二维/多维张量的交换维度，返回输入张量的转置版本，但是只能实现两个维度的交换。

In [65]:
a.shape

torch.Size([4, 1, 28, 28])

In [66]:
# 交换第 2 和第 4 维度
a.transpose(1, 3).shape

torch.Size([4, 28, 28, 1])

注意：transpose() 对张量进行了转置，数据的顺序发生了变化，所以当我们使用 view() 先压缩 shape 再恢复 shape 时，在恢复步骤中，必须先恢复为压缩之前的 shape，若恢复为其他 shape，会造成数据污染。这一点，我们要格外注意！！！

In [67]:
# 交换维度 size 之后，再使用 view() reshape，直接 reshape 为 a 的形状（错误的方法）
a1 = a.transpose(1, 3).contiguous().view(4, 1*28*28).view(4, 1, 28, 28)  # 在张量处于转置状态，数据的顺序发生了变化的情况下，直接 reshape 为 a 的形状是错误的，得到的结果不同于 a

# 交换维度 size 之后，再使用 view() reshape，先 reshape 恢复，再使用 transpose() 恢复为 a 的形状（正确的方法）
a2 = a.transpose(1, 3).contiguous().view(4, 1*28*28).view(4, 28, 28, 1).transpose(1, 3)

contiguous() 的作用：数据转置之后，内存顺序被打乱了，contiguous() 可以将数据复制到一个新的内存位置，使内存顺序重新连续起来。

In [68]:
a1.shape, a2.shape

(torch.Size([4, 1, 28, 28]), torch.Size([4, 1, 28, 28]))

In [69]:
# 检查 a1, a2 与 a 是否相同
torch.all(torch.eq(a1, a)), torch.all(torch.eq(a2, a))

(tensor(False), tensor(True))

`torch.eq(a1, a)`：这个函数比较 a1 中的每个元素与 a 中的每个元素，返回一个同样形状的布尔张量，其中元素为 True 表示 a1 中对应的元素等于 a，False 表示不等于。

`torch.all(...)`：这个函数检查传入的布尔张量中的所有元素是否都是 True。如果是，返回 True；否则返回 False。

## 4.8 permute(): 交换维度 size

`transpose()` 只能实现两个维度的交换，`permute()` 可以实现张量多个维度的交换（可以理解为多次 `transpose()` 交换），返回输入张量的转置版本。

In [70]:
a.shape

torch.Size([4, 1, 28, 28])

In [71]:
# 将第二个维度移至最后面
# 使用 transpose()
A1 = a.transpose(1, 2).transpose(2, 3)

# 使用 permute()
A2 = a.permute(0, 2, 3, 1)

A1.shape, A2.shape, torch.all(torch.eq(A1, A2))

(torch.Size([4, 28, 28, 1]), torch.Size([4, 28, 28, 1]), tensor(True))

# 5. 合并与分割

## 5.1 cat()

cat：在某一维度上对两个张量进行合并，不创建新的维度，要求张量其他维度的 size 须相等。

In [72]:
a = torch.rand(4, 32, 8)
b = torch.rand(5, 32, 8)

torch.cat([a,b], dim=0).shape

torch.Size([9, 32, 8])

## 5.2 stack()

stack：对两个张量进行合并时创建一个新的维度，新维度的意义由自己指定，要求张量各个维度的 size 须相等。

In [73]:
a = torch.rand(4, 32, 8)
b = torch.rand(4, 32, 8)

torch.stack([a,b], dim=0).shape

torch.Size([2, 4, 32, 8])

## 5.3 split()

split：既可以指定拆分的 step 长度，也可以指定拆分得到的各块的数量。

In [74]:
a = torch.rand(6, 32, 8)

In [75]:
# 指定 step=2
a1, a2, a3 = a.split(2, dim=0)
a1.shape, a2.shape, a3.shape

(torch.Size([2, 32, 8]), torch.Size([2, 32, 8]), torch.Size([2, 32, 8]))

In [76]:
# 指定拆分得到的各块的数量
a1, a2, a3 = a.split([1,2,3], dim=0)
a1.shape, a2.shape, a3.shape

(torch.Size([1, 32, 8]), torch.Size([2, 32, 8]), torch.Size([3, 32, 8]))

## 5.4 chunk()

chunk：直接指定要拆分为几块，被拆分的维度的 size 须被指定的数整除。

In [77]:
a = torch.rand(6, 32, 8)

In [78]:
a1, a2 = a.chunk(2, dim=0)  # 拆分为 2 块
a1.shape, a2.shape

(torch.Size([3, 32, 8]), torch.Size([3, 32, 8]))

# 6. 数学运算

## 6.1 加减乘除

张量的加减除可以直接使用 + - /

乘法：* 表示两个张量的对位元素相乘（element-wise）；@ 和 `torch.matmul()` 表示矩阵乘法。

+: add

-: sub

*: mul

/: div

@: matmul

In [79]:
a = torch.full([2,3], 2)
b = torch.full([2,3], 3)

print(a), print(b), print("\n")
print(a+b), print(torch.add(a,b)), print("\n")
print(b-a), print(torch.sub(b,a)), print("\n")
print(b/a), print(torch.div(b,a)), print("\n")
print(a*b), print(torch.mul(a,b)), print("\n")
a@b.t()

tensor([[2, 2, 2],
        [2, 2, 2]])
tensor([[3, 3, 3],
        [3, 3, 3]])


tensor([[5, 5, 5],
        [5, 5, 5]])
tensor([[5, 5, 5],
        [5, 5, 5]])


tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[1, 1, 1],
        [1, 1, 1]])


tensor([[1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000]])
tensor([[1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000]])


tensor([[6, 6, 6],
        [6, 6, 6]])
tensor([[6, 6, 6],
        [6, 6, 6]])




tensor([[18, 18],
        [18, 18]])

## 6.2 矩阵乘法

多维张量的矩阵乘法只看最后两个维度。

多维张量的矩阵乘法可以使用 @ 和 `torch.matmul()`，两者是等价的。

In [80]:
a = torch.rand(4, 3, 28, 64)
b = torch.rand(4, 3, 64, 32)

(a @ b).shape, torch.matmul(a, b).shape

(torch.Size([4, 3, 28, 32]), torch.Size([4, 3, 28, 32]))

## 6.3 幂运算和 log 运算

In [81]:
a = torch.full([2,3], 2)

In [82]:
a.pow(3), a**3

(tensor([[8, 8, 8],
         [8, 8, 8]]),
 tensor([[8, 8, 8],
         [8, 8, 8]]))

In [83]:
b = torch.exp(a)  # 以 e 为底数，张量 a 的元素为指数
b

tensor([[7.3891, 7.3891, 7.3891],
        [7.3891, 7.3891, 7.3891]])

In [84]:
# log 对数运算
torch.log(b)  # log 代表 ln，以 2 为底数可以写为 log2，以 10 为底数可以写为 log10

tensor([[2., 2., 2.],
        [2., 2., 2.]])

## 6.4 约数运算

In [85]:
# 向下取整，向上取整，返回浮点数的整数部分，返回浮点数的小数部分
a = torch.tensor(3.14)
a.floor(), a.ceil(), a.trunc(), a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [86]:
# 四舍五入
a = torch.tensor(3.499)
b = torch.tensor(3.5)
a.round(), b.round()

(tensor(3.), tensor(4.))