# 1. Python 列表 VS PyTorch 张量

# 2. 创建一个张量

In [1]:
import torch
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

# 3. PyTorch 张量的存储区

In [2]:
# 可以使用 storage() 访问张量的存储区
points.storage()

C:\Users\24606\AppData\Local\Temp\ipykernel_14512\4262897667.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [3]:
# 使用索引访问存储区的一维数组
points.storage()[0]

4.0

In [4]:
# 修改存储区的值
points.storage()[1] = 8
points.storage()

 4.0
 8.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

# 4. 张量的数字类型

In [5]:
# 张量的默认数据类型是 32 位浮点数
points.dtype

torch.float32

In [6]:
# 构造张量时使用 dtype 指定数字类型
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
double_points.dtype, short_points.dtype

(torch.float64, torch.int16)

In [7]:
# 使用 to() 方法将张量创建函数的输出转换为正确的类型
double_points = torch.ones(10, 2).to(dtype=torch.double)
double_points.dtype

# 在底层，to() 方法会检查转换是否是必要的，如果必要，则执行转换。

torch.float64

# 5. 将张量存储到 GPU 上

In [8]:
# 在 GPU 上创建一个张量
# points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [9]:
# 使用 to() 方法将在 CPU 上创建的张量复制到 GPU 上
# points_gpu = points.to(device='cuda')

# 6. to() 方法

In [10]:
# 使用 to() 方法将张量创建函数的输出转换为正确的类型
double_points = torch.ones(10, 2).to(dtype=torch.double)
double_points.dtype

# 在底层，to() 方法会检查转换是否是必要的，如果必要，则执行转换。

torch.float64

In [11]:
# 使用 to() 方法将在 CPU 上创建的张量复制到 GPU 上
# points_gpu = points.to(device='cuda')

In [12]:
# 通过 device 和 dtype 参数同时更改位置和数据类型
# double_points_gpu = torch.ones(10, 2).to(device='cuda', dtype=torch.double)

# 7. PyTorch 张量和 NumPy 数组的互相转换

In [13]:
import numpy as np
A = np.ones((3, 2))
A.dtype

dtype('float64')

In [14]:
# 将 NumPy 数组转为 PyTorch 张量
A_tensor = torch.from_numpy(A)
A_tensor  # dtype=torch.float64

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [15]:
print(A_tensor)

# 修改 A，看 A_tensor 是否变化
A[0, 0] = 2
print(A_tensor)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[2., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


In [16]:
# 我们需要确保转换得到的张量的数据类型是 32 位浮点数（torch.float32）（张量的默认数据类型）
A_tensor = torch.from_numpy(A).to(dtype=torch.float32)
A_tensor.dtype

torch.float32

In [17]:
# 将 PyTorch 张量转为 NumPy 数组
points_np = points.numpy()
points_np

array([[4., 8.],
       [5., 3.],
       [2., 1.]], dtype=float32)

# 8. 给张量数据添加一个新的维度：批次维度，批次大小为1

In [18]:
points

tensor([[4., 8.],
        [5., 3.],
        [2., 1.]])

In [19]:
# 方法一
points = points[None]
points.shape

torch.Size([1, 3, 2])

In [20]:
# 方法二
points = torch.unsqueeze(points, 0)  # 在张量的最前面（索引为 0）添加一个新的批次维度，其中批次大小为1
points.shape

torch.Size([1, 1, 3, 2])

In [21]:
points

tensor([[[[4., 8.],
          [5., 3.],
          [2., 1.]]]])