In [1]:
import torch

# 1. 创建张量 1

In [2]:
# 创建 0 维张量（标量）
a = torch.tensor(2)
a, a.shape, a.dim()

(tensor(2), torch.Size([]), 0)

In [3]:
# 创建 1 维张量
b = torch.tensor([1, 2])
b, b.shape, b.dim()

(tensor([1, 2]), torch.Size([2]), 1)

In [4]:
# 创建 2 维张量
c = torch.rand(2, 3)  # torch.rand 是从均匀分布 [0, 1) 中随机采样
c, c.shape, c.dim()

(tensor([[0.9194, 0.6271, 0.2808],
         [0.7320, 0.6281, 0.4731]]),
 torch.Size([2, 3]),
 2)

In [5]:
# 创建 3 维张量
d = torch.rand(2, 3, 4)
d, d.shape, d.dim()

(tensor([[[0.2893, 0.3904, 0.6273, 0.4768],
          [0.5112, 0.7446, 0.3414, 0.9738],
          [0.1697, 0.6963, 0.9727, 0.0128]],
 
         [[0.2107, 0.3342, 0.1034, 0.9384],
          [0.1644, 0.5735, 0.8205, 0.2774],
          [0.6532, 0.4189, 0.7702, 0.5879]]]),
 torch.Size([2, 3, 4]),
 3)

In [6]:
# 创建 4 维张量
e = torch.rand(2, 3, 4, 5)
e, e.shape, e.dim()

(tensor([[[[0.6593, 0.8313, 0.0643, 0.0564, 0.9152],
           [0.9571, 0.6830, 0.5699, 0.4414, 0.3250],
           [0.9516, 0.1255, 0.5385, 0.5933, 0.1757],
           [0.7766, 0.8023, 0.4115, 0.2655, 0.3962]],
 
          [[0.1147, 0.8526, 0.0408, 0.5155, 0.3318],
           [0.0611, 0.2794, 0.9503, 0.2847, 0.1292],
           [0.6068, 0.5457, 0.2178, 0.1868, 0.5282],
           [0.7908, 0.0092, 0.3482, 0.4543, 0.9204]],
 
          [[0.0646, 0.6199, 0.3136, 0.6762, 0.9026],
           [0.9862, 0.3748, 0.7697, 0.2156, 0.0947],
           [0.8033, 0.0238, 0.3931, 0.0034, 0.2784],
           [0.6479, 0.0881, 0.3155, 0.5171, 0.3847]]],
 
 
         [[[0.8824, 0.5544, 0.2445, 0.5324, 0.0829],
           [0.9841, 0.3336, 0.6787, 0.1338, 0.3169],
           [0.6381, 0.6531, 0.6902, 0.4889, 0.4793],
           [0.9444, 0.7151, 0.8803, 0.3191, 0.9562]],
 
          [[0.3138, 0.5245, 0.3233, 0.2029, 0.8954],
           [0.9185, 0.0768, 0.7811, 0.6814, 0.0825],
           [0.4816, 0.3676, 0.9

In [7]:
e.numel()  # number of element, 2*3*4*5=120

120

In [8]:
# 设置张量的默认数据类型
# torch.set_default_tensor_type(torch.DoubleTensor)

# 2. 创建张量 2

## 2.1 从分布中随机采样

In [9]:
# 从均匀分布 [0, 1) 中随机采样
a = torch.rand(2, 3)  
a

tensor([[0.4449, 0.8131, 0.9448],
        [0.1396, 0.7022, 0.2286]])

In [10]:
# 从 [1, 10) 中随机采样整数
torch.randint(1, 10, [3,4])  

tensor([[5, 4, 6, 8],
        [4, 5, 6, 7],
        [1, 1, 2, 8]])

In [11]:
# 从标准正态分布 N(0, 1) 中随机采样
torch.randn(3, 4)  # 3 行 4 列

tensor([[-1.2475, -1.1193, -0.6622, -0.9806],
        [-0.8329, -0.5296, -0.3041,  0.9570],
        [-0.9947, -0.4797,  0.7994,  1.6489]])

In [12]:
# 从正态分布中随机采样
torch.normal(mean=0, std=4, size=(2, 3))

tensor([[-2.1019, -0.3330, -0.2466],
        [-2.7793,  2.4186, -9.1473]])

## 2.2 使用特定值填充张量

In [13]:
# 使用任意值填充张量
torch.full([2,3], 6)  # 2 行 3 列，填充值为 6

tensor([[6, 6, 6],
        [6, 6, 6]])

In [14]:
# 使用 1 填充张量
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [15]:
# 使用 0 填充张量
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
# 使用 1 填充张量对角线
torch.eye(3, 4)  # 使用 1 填充 3 行 4 列张量对角线

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

## 2.3 生成序列张量

In [17]:
# 生成整数序列张量
torch.arange(0, 10, 2)  # 采样 [0,10) 之间的整数，步长为 2，默认为 1

tensor([0, 2, 4, 6, 8])

In [18]:
# 生成等间隔序列张量
torch.linspace(0, 10, steps=4)  # 起始值为 0, 结束值为 10, steps 指定生成的样本数量为 4

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [19]:
# 生成等间隔序列张量，并使用指定底数做指数运算
torch.logspace(0, 10, steps=11, base=2)  # 起始值为 0, 结束值为 10, base 指定底数为 2，默认为 10

tensor([1.0000e+00, 2.0000e+00, 4.0000e+00, 8.0000e+00, 1.6000e+01, 3.2000e+01,
        6.4000e+01, 1.2800e+02, 2.5600e+02, 5.1200e+02, 1.0240e+03])

## 2.4 生成随机索引种子张量

In [20]:
idx = torch.randperm(10)  # 范围为 [0, 10)
idx

tensor([9, 7, 8, 0, 5, 6, 4, 3, 2, 1])

# 3. 索引与切片

In [21]:
a = torch.rand(3, 4, 18, 5)
b = torch.randn(3, 4)

## 3.1 直接索引

In [22]:
a[0].shape

torch.Size([4, 18, 5])

In [23]:
a[0, 0].shape

torch.Size([18, 5])

In [24]:
a[0, 0, 2, 4].shape

torch.Size([])

## 3.2 切片

In [25]:
a.shape

torch.Size([3, 4, 18, 5])

In [26]:
a[:2].shape

torch.Size([2, 4, 18, 5])

In [27]:
a[:2, :1, :, :].shape

torch.Size([2, 1, 18, 5])

In [28]:
a[:2, 1:, :, :].shape

torch.Size([2, 3, 18, 5])

In [29]:
a[:2, -1:, :, :].shape

torch.Size([2, 1, 18, 5])

In [30]:
a[:, :-1, :, :].shape

torch.Size([3, 3, 18, 5])

## 3.3 间隔采样

In [31]:
a.shape

torch.Size([3, 4, 18, 5])

In [32]:
a[:, :, 0:18:2, :].shape

torch.Size([3, 4, 9, 5])

In [33]:
a[:, :, ::2, :].shape  # ::2 表示从全序列采样，每 2 个采样一次

torch.Size([3, 4, 9, 5])

## 3.4 根据特定索引采样

In [34]:
a.shape

torch.Size([3, 4, 18, 5])

In [35]:
a.index_select(2, torch.tensor([2,5,7,15])).shape

torch.Size([3, 4, 4, 5])

## 3.5 根据掩码采样

In [36]:
b

tensor([[ 1.5628,  0.8783, -1.3608, -0.3513],
        [ 0.6636, -0.3566, -1.3542, -0.4308],
        [ 1.0327,  0.4493, -0.8951, -1.7003]])

In [37]:
mask = b.ge(0.5)  # great equal 为大于等于，取 b 中大于等于 0.5 的元素
mask

tensor([[ True,  True, False, False],
        [ True, False, False, False],
        [ True, False, False, False]])

In [38]:
torch.masked_select(b, mask)

tensor([1.5628, 0.8783, 0.6636, 1.0327])

## 3.6 打平之后采样

In [39]:
b

tensor([[ 1.5628,  0.8783, -1.3608, -0.3513],
        [ 0.6636, -0.3566, -1.3542, -0.4308],
        [ 1.0327,  0.4493, -0.8951, -1.7003]])

In [40]:
torch.take(b, torch.tensor([0, 3, 10, 11]))

tensor([ 1.5628, -0.3513, -0.8951, -1.7003])

## 3.7 ... 全取

In [41]:
a.shape

torch.Size([3, 4, 18, 5])

In [42]:
a[2, ...].shape  # 第 1 维取的是索引为 2 的内容，其余维度的内容全取

torch.Size([4, 18, 5])

In [43]:
a[:, 3, ...].shape

torch.Size([3, 18, 5])

In [44]:
a[..., :3].shape

torch.Size([3, 4, 18, 3])

In [45]:
a[2:, ..., :3].shape

torch.Size([1, 4, 18, 3])

# 4. 维度变换 

In [46]:
a = torch.rand(4, 1, 28, 28)

## 4.1 view() 和 reshape()：重塑数据 shape，两者完全等同

In [47]:
a.view(4, 1*28*28)  # 变换成 2 维

tensor([[0.8549, 0.8533, 0.4370,  ..., 0.8708, 0.7496, 0.4803],
        [0.0984, 0.1370, 0.7975,  ..., 0.8660, 0.7602, 0.1966],
        [0.7330, 0.7013, 0.9272,  ..., 0.8054, 0.4587, 0.5118],
        [0.9870, 0.5060, 0.4710,  ..., 0.3338, 0.4595, 0.8361]])

In [48]:
a.reshape(4, 1*28*28)

tensor([[0.8549, 0.8533, 0.4370,  ..., 0.8708, 0.7496, 0.4803],
        [0.0984, 0.1370, 0.7975,  ..., 0.8660, 0.7602, 0.1966],
        [0.7330, 0.7013, 0.9272,  ..., 0.8054, 0.4587, 0.5118],
        [0.9870, 0.5060, 0.4710,  ..., 0.3338, 0.4595, 0.8361]])

## 4.2 unsqueeze(): 增加维度

In [49]:
a.shape

torch.Size([4, 1, 28, 28])

In [50]:
a.unsqueeze(0).shape  # 在第一维之前增加一个维度

torch.Size([1, 4, 1, 28, 28])

In [51]:
a.unsqueeze(-1).shape  # 在最后一维之后增加一个维度

torch.Size([4, 1, 28, 28, 1])

In [52]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [53]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

## 4.3 squeeze(): 减少维度

In [54]:
a.shape

torch.Size([4, 1, 28, 28])

In [55]:
a.squeeze().shape

torch.Size([4, 28, 28])

In [56]:
a.squeeze(1).shape  

torch.Size([4, 28, 28])

In [57]:
a.squeeze(0).shape  

torch.Size([4, 1, 28, 28])

In [58]:
a.squeeze(-3).shape  

torch.Size([4, 28, 28])

## 4.4 expand(): 增加某一维度的 size

In [59]:
a.shape, a.numel()

(torch.Size([4, 1, 28, 28]), 3136)

In [60]:
a.expand(4, 2, 28, 28).shape, a.expand(4, 2, 28, 28).numel()

(torch.Size([4, 2, 28, 28]), 6272)

In [61]:
a.expand(-1, 2, -1, -1).shape

torch.Size([4, 2, 28, 28])

## 4.5 使用示例：不同维度数据相加

In [62]:
# 创建一个包含 32 个数据的一维张量
b = torch.rand(32)

# 创建一个四维张量，其中第二维的 size 为 32
c = torch.rand(4, 32, 15, 15)

# 使用 unsqueeze() 增加 b 的维度
b = b.unsqueeze(0).unsqueeze(2).unsqueeze(3)

# 使用 expand() 增加 b 的维度的 size
b = b.expand(4, 32, 15, 15)

# 将 b 和 c 相加
(b + c).shape

torch.Size([4, 32, 15, 15])

## 4.6 t(): 交换维度

In [63]:
d = torch.rand(3, 4)

In [64]:
d.t().shape

torch.Size([4, 3])

## 4.7 transpose(): 交换维度

In [65]:
a.shape

torch.Size([4, 1, 28, 28])

In [66]:
# 交换第 2 和第 4 维度
a.transpose(1, 3).shape

torch.Size([4, 28, 28, 1])

In [67]:
# 交换维度 size 之后，再使用 view() reshape，直接 reshape 为 a 的形状（错误的方法）
a1 = a.transpose(1, 3).contiguous().view(4, 1*28*28).view(4, 1, 28, 28)  # 在张量处于转置状态，数据的顺序发生了变化的情况下，直接 reshape 为 a 的形状是错误的，得到的结果不同于 a

# 交换维度 size 之后，再使用 view() reshape，先 reshape 恢复，再使用 transpose() 恢复为 a 的形状（正确的方法）
a2 = a.transpose(1, 3).contiguous().view(4, 1*28*28).view(4, 28, 28, 1).transpose(1, 3)

In [68]:
a1.shape, a2.shape

(torch.Size([4, 1, 28, 28]), torch.Size([4, 1, 28, 28]))

In [69]:
# 检查 a1, a2 与 a 是否相同
torch.all(torch.eq(a1, a)), torch.all(torch.eq(a2, a))

(tensor(False), tensor(True))

## 4.8 permute(): 交换维度 size

In [70]:
a.shape

torch.Size([4, 1, 28, 28])

In [71]:
# 将第二个维度移至最后面
# 使用 transpose()
A1 = a.transpose(1, 2).transpose(2, 3)

# 使用 permute()
A2 = a.permute(0, 2, 3, 1)

A1.shape, A2.shape, torch.all(torch.eq(A1, A2))

(torch.Size([4, 28, 28, 1]), torch.Size([4, 28, 28, 1]), tensor(True))

# 5. 合并与分割

## 5.1 cat()

In [72]:
a = torch.rand(4, 32, 8)
b = torch.rand(5, 32, 8)

torch.cat([a,b], dim=0).shape

torch.Size([9, 32, 8])

## 5.2 stack()

In [73]:
a = torch.rand(4, 32, 8)
b = torch.rand(4, 32, 8)

torch.stack([a,b], dim=0).shape

torch.Size([2, 4, 32, 8])

## 5.3 split()

In [74]:
a = torch.rand(6, 32, 8)

In [75]:
# 指定 step=2
a1, a2, a3 = a.split(2, dim=0)
a1.shape, a2.shape, a3.shape

(torch.Size([2, 32, 8]), torch.Size([2, 32, 8]), torch.Size([2, 32, 8]))

In [76]:
# 指定拆分得到的各块的数量
a1, a2, a3 = a.split([1,2,3], dim=0)
a1.shape, a2.shape, a3.shape

(torch.Size([1, 32, 8]), torch.Size([2, 32, 8]), torch.Size([3, 32, 8]))

## 5.4 chunk()

chunk：直接指定要拆分为几块，被拆分的维度的 size 须被指定的数整除。

In [77]:
a = torch.rand(6, 32, 8)

In [78]:
a1, a2 = a.chunk(2, dim=0)  # 拆分为 2 块
a1.shape, a2.shape

(torch.Size([3, 32, 8]), torch.Size([3, 32, 8]))

# 6. 数学运算

## 6.1 加减乘除

In [79]:
a = torch.full([2,3], 2)
b = torch.full([2,3], 3)

a, b, a+b, b-a, b/a, a*b, a@b.t()

(tensor([[2, 2, 2],
         [2, 2, 2]]),
 tensor([[3, 3, 3],
         [3, 3, 3]]),
 tensor([[5, 5, 5],
         [5, 5, 5]]),
 tensor([[1, 1, 1],
         [1, 1, 1]]),
 tensor([[1.5000, 1.5000, 1.5000],
         [1.5000, 1.5000, 1.5000]]),
 tensor([[6, 6, 6],
         [6, 6, 6]]),
 tensor([[18, 18],
         [18, 18]]))

## 6.2 矩阵乘法

In [80]:
a = torch.rand(4, 3, 28, 64)
b = torch.rand(4, 3, 64, 32)

(a @ b).shape, torch.matmul(a, b).shape

(torch.Size([4, 3, 28, 32]), torch.Size([4, 3, 28, 32]))

## 6.3 幂运算和 log 运算

In [81]:
a = torch.full([2,3], 2)

In [82]:
a.pow(3), a**3

(tensor([[8, 8, 8],
         [8, 8, 8]]),
 tensor([[8, 8, 8],
         [8, 8, 8]]))

In [83]:
b = torch.exp(a)  # 以 e 为底数，张量 a 的元素为指数
b

tensor([[7.3891, 7.3891, 7.3891],
        [7.3891, 7.3891, 7.3891]])

In [84]:
# log 对数运算
torch.log(b)  # log 代表 ln，以 2 为底数可以写为 log2，以 10 为底数可以写为 log10

tensor([[2., 2., 2.],
        [2., 2., 2.]])

## 6.4 约数运算

In [85]:
# 向下取整，向上取整，返回浮点数的整数部分，返回浮点数的小数部分
a = torch.tensor(3.14)
a.floor(), a.ceil(), a.trunc(), a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [86]:
# 四舍五入
a = torch.tensor(3.499)
b = torch.tensor(3.5)
a.round(), b.round()

(tensor(3.), tensor(4.))