In [2]:
import torch

In [3]:
torch.version.__version__

'2.5.1+cpu'

In [4]:
a = torch.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [5]:
b = torch.ones(3,3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
a + b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [7]:
# 电脑有显卡时以下代码才可用
# a = a.to('cuda')
# b = b.to('cuda')
# a + b